### ISSUE TITLE
FrontEnd Roadmap

### ISSUE THREAD

**Issue by JollyRen** [ReactThreeShowroom/frontend#9]
- [ ] Customer can:
  - [ ] log in
  - [ ] sign up
  - [ ] log out
  - [ ] view account
  - [ ] view past clients
  - [ ] view choices client choices
  - [ ] view choices as client
  - [ ] sign up for subscription
- [ ] Subbed Customer can:
  - [ ] go to showroom
  - [ ] make a new view
  - [ ] save view as client choice
  - [ ] view client choices
- [ ] Showroom:
  - [ ] loads type
  - [ ] subtype
  - [ ] pattern
  - [ ] color
  - [ ] matte/glossy option
  - [ ] Add client info
  - [ ] create client choice
  - [ ] edit client choice
  - [ ] load client choice
- [ ] Admin can:
  - [ ] view customer data
  - [ ] view clients (applicators)
  - [ ] view saved client choices
  - [ ] view subscriptions
  - [ ] cancel subscriptions
  - [ ] has dashboard for above data
